spring:
  datasource:
    url: jdbc:log4jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          lob:non_contextual_creation: true

  thymeleaf:
    cache: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  main:
    allow-bean-definition-overriding: true

logging:
  config: classpath:log4j2.xml
  level:
    web: OFF
    jdbc.sqlonly: OFF
    jdbc.sqltiming: DEBUG
    jdbc.audit: OFF
    jdbc.resultset: OFF
    jdbc.resultsettable: OFF
    jdbc.connection: OFF
    org.hibernate.SQL: OFF
    org.springframework.web: OFF
    org.springframework.boot.autoconfigure: INFO
    com.zaxxer.hikari.HikariDataSource: ERROR
    org.springframework.jdbc.core.JdbcTemplate: OFF
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

mybatis:
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true